// examples/react-vite/src/App.jsx
import { Footer, Header } from "brand-shell";
import "brand-shell/default.css";

import contract from "../../shared/brand-contract.json";

const { details, theme } = contract;

export default function App() {
  return (
    <div className="demo-app">
      <Header details={details} theme={theme} />
      <main className="demo-main demo-layout-main">
        <h1>React Demo</h1>
        <p>
          This app uses the React adapter and the shared contract from
          <code> examples/shared/brand-contract.json</code>.
        </p>
      </main>
      <Footer details={details} theme={theme} />
    </div>
  );
}

// examples/svelte-vite/src/App.svelte
<script>
  import { brandShell } from "brand-shell/svelte";
  import "brand-shell/default.css";

  import contract from "../../shared/brand-contract.json";

  const shellProps = {
    details: contract.details,
    theme: contract.theme,
  };
</script>

<div class="demo-app">
  <brand-header use:brandShell={shellProps}></brand-header>
  <main class="demo-main demo-layout-main">
    <h1>Svelte Demo</h1>
    <p>
      This app uses <code>brand-shell/svelte</code> and the shared contract from
      <code>examples/shared/brand-contract.json</code>.
    </p>
  </main>
  <brand-footer use:brandShell={shellProps}></brand-footer>
</div>
